[package]
name = "kifuwarabe_wcsc29_lib"
version = "0.1.0"
authors = ["むずでょ <muzudho1@gmail.com>"]

[dependencies]
rand = "0.6.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
getopts = "0.2"
regex = "1"
chrono = "0.4.6"
